### PR TITLE
381524 Declare cosmos database & container variables

### PR DESCRIPTION
**Pull request by rtasalem**
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/381524

### CODE REVIEW

**Comment by rtasalem** [comment]
Purpose of this PR was to declare the name of the Cosmos database (`ffc-sfd-customer-receiver-payments`) and container (`payments-container`) in the config so the `COSMOS_PAYMENTS_DATABASE` and `COSMOS_PAYMENTS_CONTAINER` variables can be removed from .env and docker-compose.yaml. Rebuilt container and tested - can confirm working as expected i.e. generic message sent through receiver is saving to Cosmos.

**Review by simonnineteen90 — COMMENTED** [review]
Same as previous PR i think we can use the `appConfig.yaml` for any values that are the same across every environment to avoid duplication

**Comment by rtasalem** [comment]
> Same as previous PR i think we can use the `appConfig.yaml` for any values that are the same across every environment to avoid duplication

@simonnineteen90 Tested a couple things out and looks like SND3 is the one that's currently successfully deploying, don't think SND4 is quite ready yet so will use SND3 until ADP inform us to move our config to SND4.

**Comment by rtasalem** [comment]
Service is now deploying with no errors in the pod logs (see screenshot below). This PR is now ready for re-review.

image

**Review by simonnineteen90 — APPROVED** [review]

**Pull request merged**
